### ISSUE TITLE
Feature parity with tartiflette-aiohttp

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-starlette#20]
**Please describe the problem**

Some features are available in `tartiflette-aiohttp`, but not yet in `tartiflette-starlette`. We want to achieve feature parity before launching `tartiflette-starlette` as an official ASGI adapter.

**Describe the solution you'd like**

Implement the following features:

- [x] #23 Quickstart code snippet that people can copy paste and get running quickly
- [x] #22 Fix default `path`
- [x] #12 GraphiQL options: `endpoint`, `default_query`, `default_variables`, `default_headers` - [tartiflette-aiohttp](https://github.com/dailymotion/tartiflette-aiohttp#enable-graphiql-handler)
- [x] #13 Extra context
- [x] #5 WebSocket subscriptions: [tutorial](https://tartiflette.io/docs/tutorial/add-subscription) - [tartiflette-aiohttp example](https://github.com/dailymotion/tartiflette-aiohttp/tree/master/examples/aiohttp/dogs)
- [x] #27 Repo banner

**Additional context**
See https://github.com/tartiflette/tartiflette-starlette/issues/19#issuecomment-492319867
