### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-starlette#59]
`tartiflette-starlette` doesn't ship type annotations yet, and those are actually wrong (running `mypy` yields a host of errors).

We need to:

- [x] Setup `mypy` for the project.
- [x] Add a `mypy` check to CI (allow to fail).
- [x] Fix all typing errors.
- [x] Enforce `mypy` to pass on CI.
- [ ] Add the `py.typed` marker file in the package and add it to `MANIFEST.in`.

All these can be contributed to independently (though in order).
